import React, { useEffect, useRef, useState } from 'react';
import { ChevronRight, CircleHelp, Check, SlidersHorizontal } from 'lucide-react';
import useStudio from '@/components/studio/useStudio';
import StudioHeader from '@/components/studio/StudioHeader';
import ToolPanel from '@/components/studio/ToolPanel';
import Inspector from '@/components/studio/Inspector';
import CanvasToolbar from '@/components/studio/CanvasToolbar';
import PlanCanvas from '@/components/studio/PlanCanvas';
import ThreePreview from '@/components/studio/ThreePreview';
import ProjectDialog from '@/components/studio/ProjectDialog';
import { downloadPlan } from '@/components/studio/designData';
import { Sheet, SheetContent, SheetTitle } from '@/components/ui/sheet';
export default function Home() {
    const s = useStudio(), svgRef = useRef(null), [view, setView] = useState('3D'), [zoom, setZoom] = useState(1), [grid, setGrid] = useState(true), [snap, setSnap] = useState(true), [dimensions, setDimensions] = useState(true), [offset, setOffset] = useState({ x: 0, y: 0 }), [dialog, setDialog] = useState(null), [properties, setProperties] = useState(false), [fitKey, setFitKey] = useState(0);
    useEffect(() => { const key = e => { if (['INPUT', 'TEXTAREA', 'SELECT'].includes(e.target.tagName) || e.target.closest?.('[contenteditable]:not([contenteditable="false"])')) return; if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'c') { if (s.copy()) e.preventDefault(); return; } if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'v') { if (s.paste()) e.preventDefault(); return; } if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'z') { e.preventDefault(); e.shiftKey ? s.redo() : s.undo(); } if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 's') { e.preventDefault(); s.save(); } if ((e.key === 'Delete' || e.key === 'Backspace') && s.selected) { e.preventDefault(); s.remove(); } if (e.key === 'Escape') { s.setTool('select'); s.setSelected(null); } }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); });
    useEffect(() => { const warn = e => { if (s.dirty) { e.preventDefault(); e.returnValue = ''; } }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn); }, [s.dirty]);
    const exportPlan = () => { if (svgRef.current) downloadPlan(svgRef.current, s.project.name + '_' + s.floor.name); };
    const load = p => { s.load(p); setView('3D'); setZoom(1); setOffset({ x: 0, y: 0 }); };
    return <div className="h-[100dvh] min-h-[540px] bg-[#f7f8f2] flex flex-col text-[#39433b]">
        <StudioHeader s={s} onProjects={() => setDialog('open')} onNew={() => setDialog('new')} onExport={exportPlan} view={view} setView={setView} />
        <div className="flex flex-1 overflow-hidden"><ToolPanel s={s} /><main className="flex flex-col flex-1 min-w-0"><CanvasToolbar {...{ s, zoom, setZoom, grid, setGrid, snap, setSnap, dimensions, setDimensions, setOffset, view, setView }} onFit={() => setFitKey(k => k + 1)} />
            <div className="px-7 py-5 flex items-start justify-between shrink-0 max-sm:px-3"><div><div className="flex items-center gap-2 text-[9px] tracking-wide text-stone-400 mb-2"><span>WORKSPACE</span><ChevronRight size={10} /><span>{s.project.building_type}</span><ChevronRight size={10} /><span>{s.floor.name}</span></div><h1 className="text-lg font-medium tracking-wide">{s.project.name}<span className="text-[10px] font-normal text-stone-400 ml-3">{s.floor.name} {view === '3D' ? '3D設計' : '平面図'}</span></h1><p className="text-[10px] text-stone-400 mt-2">{view === '3D' ? '3D空間で、直接つくる。動かす。整える。' : '暮らしのかたちを、ここから。'}</p></div><div className="flex gap-3 items-center"><span className="hidden sm:flex items-center gap-1.5 text-[9px] text-stone-400 mt-2">{s.dirty ? <span className="w-1.5 h-1.5 rounded-full bg-amber-400" /> : <Check size={12} />} {s.dirty ? '未保存の変更' : s.project.id ? '保存済み' : 'テンプレート'}</span><button onClick={() => setProperties(true)} title="プロパティを編集" className="lg:hidden p-2 border bg-white rounded-lg"><SlidersHorizontal size={15} /></button></div></div>
            <div className="flex-1 relative min-h-0 overflow-hidden"><div className={view === '2D' ? 'absolute inset-0' : 'absolute inset-0 invisible pointer-events-none'}><PlanCanvas {...{ s, svgRef, zoom, grid, snap, dimensions, offset, setOffset }} /></div>{view === '3D' && <ThreePreview {...{ s, snap, grid, dimensions, zoom, fitKey }} />}{view === '2D' && <div className="absolute bottom-4 left-1/2 -translate-x-1/2 bg-white/95 border border-[#e4e8de] rounded-full px-4 py-2.5 flex items-center gap-2 text-[10px] text-stone-500 shadow-sm max-sm:w-[90%] max-sm:justify-center"><CircleHelp size={13} className="shrink-0" />{s.tool === 'select' ? 'クリックで選択 · ドラッグで移動' : s.tool === 'pan' ? 'ドラッグして図面を移動' : '図面をクリックして配置 · 部屋と壁はドラッグで描画'}</div>}</div>
            <div className="h-10 border-t bg-[#fbfcf8] flex items-center justify-between px-6 text-[9px] text-stone-400 shrink-0"><div className="flex items-center gap-2">{s.project.floors.map(f => <button key={f.id} onClick={() => { s.setFloorId(f.id); s.setSelected(null); }} className={`px-3 py-1.5 rounded ${f.id === s.floor.id ? 'bg-[#eaf0e5] text-[#55754f]' : 'hover:bg-stone-100'}`}>{f.name}</button>)}<button onClick={s.addFloor} className="p-1" title="階を追加">＋</button><button onClick={() => setDialog('new')} className="lg:hidden ml-2">新規作成</button></div><span className="hidden sm:block">{snap ? 'スナップ : 100 mm ＋ 近接吸着 200 mm' : 'スナップ : OFF'} · 寸法入力 : m</span></div>
        </main><Inspector s={s} /></div><footer className="h-7 bg-white border-t flex justify-between items-center px-5 text-[9px] text-stone-400 shrink-0"><span className={s.error ? 'text-red-500' : 'text-[#688563]'}>{s.error || s.message || '● 設計ワークスペース'}</span><span>概念設計用 · 実施工には建築士の確認が必要です</span></footer>
        <ProjectDialog mode={dialog} onClose={() => setDialog(null)} onLoad={load} dirty={s.dirty} /><Sheet open={properties} onOpenChange={setProperties}><SheetContent className="p-0 w-80"><SheetTitle className="sr-only">プロパティ</SheetTitle><Inspector s={s} mobile /></SheetContent></Sheet>
    </div>;
}