export const uid = () => crypto.randomUUID();
export const tools = [{ id: 'select', name: '選択', icon: 'MousePointer2' }, { id: 'room', name: '部屋', icon: 'Square' }, { id: 'wall', name: '壁', icon: 'Minus' }, { id: 'door', name: 'ドア', icon: 'DoorOpen' }, { id: 'window', name: '窓', icon: 'PanelTop' }, { id: 'column', name: '柱', icon: 'Columns3' }, { id: 'stairs', name: '階段', icon: 'Footprints' }, { id: 'furniture', name: '家具', icon: 'Armchair' }];
export const colors = ['#ece7dc', '#dde7df', '#dfe8eb', '#eae2d9', '#e5e1ec', '#f1ead4'];
export const defaults = { room: [3, 3, '部屋', colors[0]], wall: [3, 0.12, '壁', '#40504c'], door: [0.9, 0.9, 'ドア', '#ffffff'], window: [1.5, 0.12, '窓', '#9bc5c1'], column: [0.3, 0.3, '柱', '#40504c'], stairs: [1, 2, '階段', '#e2e5df'], furniture: [2, 0.85, 'ソファ', '#b7c5b7'] };
const item = (type, name, x, y, w, h, color) => ({ id: uid(), type, name, x, y, w, h, color });
export function newProject(type = '一軒家', blank = false) {
    const rooms = type === 'ビル' ? [['オフィス', 1, 1, 6, 5, colors[1]], ['会議室', 7, 1, 4, 3, colors[2]], ['エントランス', 7, 4, 4, 2, colors[0]], ['共用スペース', 1, 6, 10, 3, colors[3]]] : [['リビング・ダイニング', 1, 1, 6, 5, colors[0]], ['洋室 01', 7, 1, 4, 3, colors[1]], ['洋室 02', 7, 4, 4, 3, colors[1]], ['キッチン', 1, 6, 3, 3, colors[3]], ['洗面・浴室', 4, 6, 3, 3, colors[2]], ['玄関・ホール', 7, 7, 4, 2, colors[0]]];
    const elements = rooms.map(r => item('room', ...r));
    elements.push(item('window', '窓', 2, 1, 2.8, 0.12, '#9bc5c1'), item('window', '窓', 8, 1, 1.8, 0.12, '#9bc5c1'), item('window', '窓', 1, 2, 0.12, 2, '#9bc5c1'), item('door', 'ドア', 7, 2.9, 0.9, 0.9, '#fff'), item('door', 'ドア', 7, 5.5, 0.9, 0.9, '#fff'), item('door', '玄関ドア', 8.5, 9, 0.9, 0.9, '#fff'), item('furniture', 'ソファ', 2, 2.1, 2.4, 0.85, '#b7c5b7'), item('furniture', 'テーブル', 4.6, 3.7, 1.4, 0.8, '#c4b59d'), item('furniture', 'ベッド', 8, 1.5, 1.6, 2, '#c7d2c7'), item('furniture', 'キッチン', 1.2, 7.6, 2.5, 0.65, '#d6c9ba'));
    return { name: type === '一軒家' ? '光が集まる家' : type === 'マンション' ? 'マンションの住まい' : 'オフィスビル計画', building_type: type, structure: type === '一軒家' ? '木造' : 'RC造', floors: [{ id: uid(), name: '1F', height: 2.7, elements: blank ? [] : elements }] };
}
export function downloadPlan(svg, name) { const copy = svg.cloneNode(true); copy.setAttribute('xmlns', 'http://www.w3.org/2000/svg'); const blob = new Blob([new XMLSerializer().serializeToString(copy)], { type: 'image/svg+xml' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = name + '.svg'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }