import React from 'react';
import { SlidersHorizontal, Copy, Trash2, House, Move, Layers3 } from 'lucide-react';
import { colors } from '@/components/studio/designData';
import { elementHeight, elementElevation } from '@/components/studio/threeGeometry';
export default function Inspector({ s, mobile = false }) {
    const e = s.floor.elements.find(e => e.id === s.selected), area = s.floor.elements.filter(e => e.type === 'room').reduce((a, e) => a + e.w * e.h, 0);
    const numeric = (label, key, value, update, min = -100, unit = 'm', max = 100) => <label key={key} className="text-[10px] text-stone-500">{label}<div className="flex border rounded-md mt-1.5 px-2.5 py-2 bg-[#fafbf8]"><input aria-label={label} type="number" step="0.1" min={min} max={max} value={value} onChange={ev => { if (ev.target.value !== '' && Number.isFinite(+ev.target.value)) update({ [key]: Math.min(max, Math.max(min, +ev.target.value)) }); }} className="w-full outline-none bg-transparent text-xs text-[#425044]" /><span className="text-[10px] text-stone-400">{unit}</span></div></label>;
    return <aside className={mobile ? 'w-full h-full bg-white overflow-y-auto p-6' : 'w-[252px] shrink-0 bg-white border-l overflow-y-auto p-5 max-xl:w-[220px] max-lg:hidden'}><div className="flex items-center gap-2 pb-5 border-b text-xs font-semibold"><SlidersHorizontal size={15} />プロパティ<span className="ml-auto text-[9px] text-stone-400">{e ? '選択中' : '全体'}</span></div>
        <div className="mt-5 flex items-center gap-3"><div className="p-2.5 rounded-lg bg-[#f1f4ee] text-[#5c775e]"><House size={19} /></div><div className="text-xs font-medium">{e ? e.name : '建物の設定'}<p className="text-[10px] font-normal text-stone-400 mt-1">{e ? '選択した要素を編集' : 'プロジェクトの基本情報'}</p></div></div>
        {e ? <><label className="block text-[10px] text-stone-500 mt-6">名称<input value={e.name} onChange={v => s.updateElement(e.id, { name: v.target.value })} className="block border bg-[#fafbf8] rounded-md p-2.5 mt-2 w-full text-xs text-stone-700" /></label><p className="text-[10px] mt-6 mb-3 flex items-center gap-2 text-stone-500"><Move size={12} />位置とサイズ</p><div className="grid grid-cols-2 gap-3">{[['X 座標', 'x', -100], ['Y 座標', 'y', -100], ['幅', 'w', 0.1], ['奥行き', 'h', 0.1]].map(([label, key, min]) => numeric(label, key, e[key], p => s.updateElement(e.id, p), min))}{numeric('高さ', 'object_height', elementHeight(e, s.floor.height), p => s.updateElement(e.id, p), 0.1)}{numeric('床からの高さ', 'elevation', elementElevation(e), p => s.updateElement(e.id, p), 0)}{numeric('回転', 'rotation', e.rotation || 0, p => s.updateElement(e.id, p), 0, '°', 360)}</div><p className="text-[10px] text-stone-500 mt-6 mb-3">塗りの色</p><div className="flex gap-2 flex-wrap">{colors.map(c => <button key={c} aria-label={`色 ${c}`} onClick={() => s.updateElement(e.id, { color: c })} style={{ background: c }} className={`h-6 w-6 rounded-full border-2 ${e.color === c ? 'border-[#55755c]' : 'border-white'}`} />)}<input aria-label="自由な色" type="color" value={e.color?.length === 7 ? e.color : '#ffffff'} onChange={v => s.updateElement(e.id, { color: v.target.value })} className="w-6 h-6" /></div><div className="flex gap-3 mt-6 border-t pt-4"><button onClick={s.duplicate} className="flex gap-2 items-center text-xs text-stone-500"><Copy size={13} />複製</button><button onClick={s.remove} className="flex gap-2 items-center text-xs text-red-400 ml-auto"><Trash2 size={13} />削除</button></div></> : <><label className="block text-[10px] text-stone-500 mt-6">プロジェクト名<input value={s.project.name} onChange={v => s.commit({ ...s.project, name: v.target.value })} className="w-full text-xs border rounded-md p-2.5 mt-2" /></label><label className="block text-[10px] text-stone-500 mt-5">建物の種類<select value={s.project.building_type} onChange={v => s.commit({ ...s.project, building_type: v.target.value })} className="w-full mt-2 border rounded-md p-2.5 text-xs">{['一軒家', 'マンション', 'ビル'].map(t => <option key={t}>{t}</option>)}</select></label><label className="block text-[10px] text-stone-500 mt-5">構造の想定<select value={s.project.structure} onChange={v => s.commit({ ...s.project, structure: v.target.value })} className="w-full mt-2 border rounded-md p-2.5 text-xs">{['木造', '鉄骨造', 'RC造'].map(t => <option key={t}>{t}</option>)}</select></label><div className="mt-5">{numeric('階高', 'height', s.floor.height, p => s.commit({ ...s.project, floors: s.project.floors.map(f => f.id === s.floor.id ? { ...f, ...p } : f) }), 0.5)}</div></>}
        <div className="mt-7 border-t pt-5"><p className="text-[10px] flex gap-2 text-stone-500 mb-4"><Layers3 size={12} />{s.floor.name} の概要</p><div className="flex justify-between text-xs mb-3"><span className="text-stone-500">部屋面積の合計</span><b className="font-medium">{area.toFixed(2)} <span className="text-[10px]">m²</span></b></div><div className="flex justify-between text-xs"><span className="text-stone-500">部屋数</span><span>{s.floor.elements.filter(e => e.type === 'room').length} 室</span></div><p className="text-[9px] text-stone-400 mt-3">重なった部屋の面積は重複して集計します。</p></div>
        <div className="mt-7 bg-[#f6f5ef] p-3 rounded-lg text-[10px] leading-relaxed text-stone-500">概念設計用のエディターです。構造安全性・耐震性・法規適合の判定や確認申請用の図面作成は行いません。実施工は建築士にご相談ください。</div></aside>;
}