import React, { useRef, useState } from 'react';
import PlanElement from '@/components/studio/PlanElement';
import { defaults, uid } from '@/components/studio/designData';
import snapPosition from '@/components/studio/snapPosition';
export default function PlanCanvas({ s, svgRef, zoom, grid, snap, dimensions, offset, setOffset }) {
    const [gesture, setGesture] = useState(null), [preview, setPreview] = useState(null), start = useRef(null);
    const vb = { x: 6 - 7 / zoom + offset.x, y: 5 - 6 / zoom + offset.y, w: 14 / zoom, h: 12 / zoom };
    const point = e => { const p = svgRef.current.createSVGPoint(); p.x = e.clientX; p.y = e.clientY; const a = p.matrixTransform(svgRef.current.getScreenCTM().inverse()); return { x: snap ? Math.round(a.x * 10) / 10 : a.x, y: snap ? Math.round(a.y * 10) / 10 : a.y }; };
    const begin = (ev, element) => { if (ev.button !== 0) return; if (element && s.tool !== 'select') return; ev.stopPropagation(); const p = point(ev); svgRef.current.setPointerCapture(ev.pointerId); start.current = { p, element, offset }; if (s.tool === 'pan') { setGesture('pan'); } else if (element) { s.setSelected(element.id); setGesture('move'); } else if (s.tool === 'select') { s.setSelected(null); } else { const [w, h, name, color] = defaults[s.tool]; const e = { id: uid(), type: s.tool, name, color, x: p.x, y: p.y, w, h }; Object.assign(e, snapPosition(e, s.floor.elements, snap)); start.current.p = { x: e.x, y: e.y }; start.current.created = e; setPreview(e); setGesture('draw'); } };
    const move = ev => { if (!gesture) return; const p = point(ev), st = start.current; if (gesture === 'pan') { setOffset({ x: offset.x + st.p.x - p.x, y: offset.y + st.p.y - p.y }); return; } if (gesture === 'move') { const e = { ...st.element, x: Math.round((st.element.x + p.x - st.p.x) * 100) / 100, y: Math.round((st.element.y + p.y - st.p.y) * 100) / 100 }; setPreview({ ...e, ...snapPosition(e, s.floor.elements, snap) }); return; } const e = st.created; let w = Math.abs(p.x - st.p.x), h = Math.abs(p.y - st.p.y); if (['room', 'wall'].includes(e.type) && w + h > 0.15) { if (e.type === 'wall') { if (w >= h) h = 0.12; else w = 0.12; } const drawn = { ...e, x: Math.min(p.x, st.p.x), y: Math.min(p.y, st.p.y), w: Math.max(0.1, w), h: Math.max(0.1, h) }; setPreview({ ...drawn, ...snapPosition(drawn, s.floor.elements, snap) }); } };
    const finish = () => { if (preview) { if (gesture === 'move') s.updateElement(preview.id, { x: preview.x, y: preview.y }); else { s.changeElements([...s.floor.elements, preview]); s.setSelected(preview.id); s.setTool('select'); } } setPreview(null); setGesture(null); start.current = null; };
    const elements = s.floor.elements.map(e => preview?.id === e.id ? preview : e).sort((a, b) => (a.type === 'room' ? 0 : 1) - (b.type === 'room' ? 0 : 1));
    const room = s.floor.elements.filter(e => e.type === 'room'); const minX = room.length ? Math.min(...room.map(e => e.x)) : 1, maxX = room.length ? Math.max(...room.map(e => e.x + e.w)) : 11, minY = room.length ? Math.min(...room.map(e => e.y)) : 1, maxY = room.length ? Math.max(...room.map(e => e.y + e.h)) : 9;
    return <svg ref={svgRef} className="w-full h-full touch-none select-none" viewBox={`${vb.x} ${vb.y} ${vb.w} ${vb.h}`} onPointerDown={e => begin(e)} onPointerMove={move} onPointerUp={finish} onPointerCancel={() => { setPreview(null); setGesture(null); }} style={{ cursor: s.tool === 'pan' ? 'grab' : s.tool === 'select' ? 'default' : 'crosshair' }}>
        <defs><pattern id="plan-grid" width="0.5" height="0.5" patternUnits="userSpaceOnUse"><path d="M 0.5 0 L 0 0 0 0.5" fill="none" stroke="#dfe3d9" strokeWidth="0.01" /><circle cx="0" cy="0" r="0.013" fill="#c4cbbd" /></pattern></defs><rect x={vb.x} y={vb.y} width={vb.w} height={vb.h} fill="#f7f8f2" />{grid && <rect x={vb.x} y={vb.y} width={vb.w} height={vb.h} fill="url(#plan-grid)" />}
        {elements.map(e => <PlanElement key={e.id} e={e} selected={e.id === s.selected} dimensions={dimensions} onPointerDown={ev => begin(ev, e)} />)}{preview && gesture === 'draw' && <g opacity="0.7"><PlanElement e={preview} selected dimensions={dimensions} /></g>}
        {dimensions && room.length > 0 && <g stroke="#8f9c8c" strokeWidth="0.015" fill="#7e8b78" pointerEvents="none"><path d={`M ${minX} ${minY - 0.45} H ${maxX} M ${minX} ${minY - 0.6} V ${minY - 0.3} M ${maxX} ${minY - 0.6} V ${minY - 0.3} M ${maxX + 0.45} ${minY} V ${maxY} M ${maxX + 0.3} ${minY} H ${maxX + 0.6} M ${maxX + 0.3} ${maxY} H ${maxX + 0.6}`} /><text x={(minX + maxX) / 2} y={minY - 0.58} fontSize="0.16" textAnchor="middle" stroke="none">{Math.round((maxX - minX) * 1000).toLocaleString()}</text><text x={maxX + 0.67} y={(minY + maxY) / 2} fontSize="0.16" textAnchor="middle" stroke="none" transform={`rotate(90 ${maxX + 0.67} ${(minY + maxY) / 2})`}>{Math.round((maxY - minY) * 1000).toLocaleString()}</text></g>}
        <g transform={`translate(${vb.x + vb.w - 1.1} ${vb.y + 0.7})`} fill="#7b8878" pointerEvents="none"><path d="M 0 0.6 L 0.16 0 L 0.32 0.6 L 0.16 0.45 Z" /><text x="0.16" y="-0.14" textAnchor="middle" fontSize="0.15">N</text></g>
    </svg>;
}