import React from 'react';
export default function PlanElement({ e, selected, onPointerDown, dimensions }) {
    const { x, y, w, h, type, color, name } = e; const stroke = selected ? '#548675' : '#45504c';
    return <g onPointerDown={onPointerDown} transform={`rotate(${e.rotation || 0} ${x + w / 2} ${y + h / 2})`} style={{ cursor: 'move' }}>
        {type === 'room' && <><rect x={x} y={y} width={w} height={h} fill={color} stroke={stroke} strokeWidth={selected ? 0.07 : 0.09} /><text x={x + w / 2} y={y + h / 2 - 0.08} textAnchor="middle" fontSize="0.19" fill="#45504c" fontWeight="500">{name}</text><text x={x + w / 2} y={y + h / 2 + 0.22} textAnchor="middle" fontSize="0.16" fill="#7d8780">{(w * h).toFixed(2)} m²</text>{dimensions && <><text x={x + w / 2} y={y + 0.3} textAnchor="middle" fontSize="0.13" fill="#939b93">{(w * 1000).toFixed(0)}</text><text x={x + 0.18} y={y + h / 2} fontSize="0.13" fill="#939b93" transform={`rotate(-90 ${x + 0.18} ${y + h / 2})`}>{(h * 1000).toFixed(0)}</text></>}</>}
        {['wall', 'column'].includes(type) && <rect x={x} y={y} width={w} height={h} fill={color} stroke={stroke} strokeWidth="0.025" />}
        {type === 'window' && <><rect x={x} y={y} width={w} height={h} fill="#f8fcfb" stroke="#76a6a1" strokeWidth="0.03" /><path d={`M ${x} ${y + h / 2} H ${x + w}`} stroke="#76a6a1" strokeWidth="0.025" /></>}
        {type === 'door' && <><path d={`M ${x} ${y} H ${x + w}`} stroke="#fafbf7" strokeWidth="0.14" /><path d={`M ${x} ${y} V ${y + h} M ${x} ${y + h} A ${w} ${h} 0 0 0 ${x + w} ${y}`} fill="none" stroke="#8f9b90" strokeWidth="0.035" /><rect x={x} y={y} width={w} height={h} fill="transparent" /></>}
        {type === 'stairs' && <><rect x={x} y={y} width={w} height={h} fill={color} stroke={stroke} strokeWidth="0.035" />{Array.from({ length: 9 }, (_, i) => <path key={i} d={`M ${x} ${y + h * i / 9} H ${x + w}`} stroke="#8f998f" strokeWidth="0.025" />)}<text x={x + w / 2} y={y + h / 2} textAnchor="middle" fontSize="0.15">↑ UP</text></>}
        {type === 'furniture' && <><rect x={x} y={y} width={w} height={h} rx="0.08" fill={color} stroke="#91a18f" strokeWidth="0.03" />{name.includes('ベッド') ? <><rect x={x + 0.1} y={y + 0.1} width={w - 0.2} height={h * 0.22} rx="0.07" fill="#f2f3ed" /><path d={`M ${x} ${y + h * 0.36} H ${x + w}`} stroke="#eef1e8" strokeWidth="0.03" /></> : name.includes('ソファ') ? <><rect x={x + 0.13} y={y + 0.15} width={w - 0.26} height={h - 0.23} rx="0.06" fill="#d4dece" /><path d={`M ${x + w / 2} ${y + 0.15} V ${y + h - 0.08}`} stroke="#a5b69f" strokeWidth="0.03" /></> : <text x={x + w / 2} y={y + h / 2 + 0.06} textAnchor="middle" fontSize="0.13" fill="#727c6c">{name}</text>}</>}
        {selected && <rect x={x - 0.08} y={y - 0.08} width={w + 0.16} height={h + 0.16} fill="none" stroke="#548675" strokeWidth="0.025" strokeDasharray="0.1 0.08" pointerEvents="none" />}
    </g>;
}