import * as THREE from 'three';
export const elementHeight = (e, H = 2.7) => e.object_height ?? ({ door: 2.1, window: 1.2, furniture: e.name.includes('ベッド') ? 0.45 : 0.7 }[e.type] ?? H);
export const elementElevation = e => e.elevation ?? (e.type === 'window' ? 0.9 : 0);
export function disposeGroup(group) { group.traverse(o => { o.geometry?.dispose(); const materials = Array.isArray(o.material) ? o.material : [o.material]; materials.filter(Boolean).forEach(m => { m.map?.dispose(); m.dispose(); }); }); group.clear(); }
function label(name, detail) { const canvas = document.createElement('canvas'); canvas.width = 640; canvas.height = 160; const c = canvas.getContext('2d'); c.fillStyle = 'rgba(255,255,255,0.97)'; c.roundRect(0, 0, 640, 160, 22); c.fill(); c.fillStyle = '#375c50'; c.font = '44px sans-serif'; c.textAlign = 'center'; c.fillText([...name].slice(0, 12).join(''), 320, detail ? 62 : 96); if (detail) { c.font = '36px sans-serif'; c.fillText(detail, 320, 122); } const texture = new THREE.CanvasTexture(canvas); texture.colorSpace = THREE.SRGBColorSpace; const sprite = new THREE.Sprite(new THREE.SpriteMaterial({ map: texture, depthTest: false })); sprite.onBeforeRender = (renderer, scene, camera) => { const distance = camera.position.distanceTo(sprite.getWorldPosition(new THREE.Vector3())), height = distance * 2 * Math.tan(THREE.MathUtils.degToRad(camera.fov / 2)) * 60 / renderer.domElement.clientHeight; sprite.scale.set(height * 4, height, 1); sprite.updateMatrixWorld(); }; sprite.renderOrder = 5; return sprite; }
export function makeElement(e, base, H, active, selected, dimensions) {
    const group = new THREE.Group(), height = elementHeight(e, H), { w, h, type } = e; group.userData = { elementId: e.id, active }; group.position.set(e.x + w / 2, base + elementElevation(e), e.y + h / 2); group.rotation.y = -THREE.MathUtils.degToRad(e.rotation || 0);
    const box = (a, b, d, x, y, z, color, opacity = 1) => { const mesh = new THREE.Mesh(new THREE.BoxGeometry(a, b, d), new THREE.MeshStandardMaterial({ color, roughness: 0.8, transparent: !active || opacity < 1, opacity: active ? opacity : 0.12, depthWrite: active && opacity === 1 })); mesh.position.set(x, y, z); group.add(mesh); return mesh; };
    if (type === 'room') { box(w, 0.08, h, 0, -0.04, 0, e.color);[[w, 0.1, 0, -h / 2], [w, 0.1, 0, h / 2], [0.1, h, -w / 2, 0], [0.1, h, w / 2, 0]].forEach(([a, d, x, z]) => box(a, height, d, x, height / 2, z, selected ? '#8cbca5' : '#d5ddd0', active ? 0.28 : 0.12)); }
    if (['wall', 'column'].includes(type)) box(w, height, h, 0, height / 2, 0, e.color);
    if (type === 'window') { box(w, height, h, 0, height / 2, 0, e.color, 0.55); box(w, 0.045, h + 0.025, 0, height / 2, 0, '#68938b'); }
    if (type === 'door') { box(w, height, 0.06, 0, height / 2, -h / 2, '#bea98e'); box(0.04, height, 0.08, -w / 2, height / 2, -h / 2, '#8b816d'); }
    if (type === 'stairs') for (let i = 0; i < 10; i++)box(w, (i + 1) * height / 10, h / 10, 0, (i + 1) * height / 20, -h / 2 + (i + 0.5) * h / 10, e.color);
    if (type === 'furniture') { box(w, height * 0.65, h, 0, height * 0.4, 0, e.color); if (e.name.includes('ソファ')) { box(w, height * 0.55, h * 0.18, 0, height * 0.72, -h * 0.4, e.color);[-1, 1].forEach(d => box(w * 0.08, height * 0.6, h, d * w * 0.46, height * 0.55, 0, e.color)); } if (e.name.includes('ベッド')) box(w * 0.86, height * 0.2, h * 0.23, 0, height * 0.8, -h * 0.3, '#f4f5ee'); }
    if (active && selected) { const edges = new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(w + 0.04, height + 0.04, h + 0.04)), new THREE.LineBasicMaterial({ color: '#3d896c', depthTest: false })); edges.position.y = height / 2; edges.renderOrder = 4; group.add(edges); }
    if (active && selected) { const sprite = label(e.name, dimensions ? `${w.toFixed(2)} × ${h.toFixed(2)} × ${height.toFixed(2)} m` : ''); sprite.position.set(0, height + 0.45, 0); group.add(sprite); }
    return group;
}
export function floorBase(project, id) { let base = 0; for (const floor of project.floors) { if (floor.id === id) return base; base += floor.height || 2.7; } return base; }
export function rebuildModel(model, project, floorId, selected, dimensions) { disposeGroup(model); let base = 0; project.floors.forEach(f => { f.elements.forEach(e => model.add(makeElement(e, base, f.height || 2.7, f.id === floorId, f.id === floorId && selected === e.id, dimensions))); base += f.height || 2.7; }); }